### ISSUE TITLE
`lporg check` command to compare

### ISSUE THREAD

**Issue by 5ouma** [blacktop/lporg#33]
I want to compare the structure from the `save` command and config file.
I tried to add this command, but the structures of output from the `save` and `load` commands.
After getting together these structures, it will be possible to compare them with the `reflect.DeepEqual()` function.

**Comment by blacktop** [comment]
what are you 'check'-ing for with this comparison?

**Comment by 5ouma** [comment]
I want to compare with the current status and `launchpad.yaml`.
In other words, to check whether I need to run `lporg load`.

**Comment by blacktop** [comment]
I tried to implement this, however, due to the fact that the ordering isn't SUPER consistent due to the Apple DB triggers and Dock app fighting me, the config ALWAYS differs from the database 😩 If we can figure out OR if my latest release has worked.  Then we can revisit this, but for now I'm closing.

**Comment by 5ouma** [comment]
How about comparing the YAML files that are specified and generated?
